# **Numpy: Part II**

In [1]:
# importing numpy
import numpy as np

### Empty Array and element selection from array

In [24]:
# making an empty array
empty = np.empty((3))
print(empty)
print('--------------')
# printing specific element from array
print(empty[0])
print('--------------')
print(empty[2])

[1.45088045e-047 1.93499724e+184 1.29441743e-312]
--------------
1.4508804500963535e-47
--------------
1.29441743275e-312


In [25]:
# multi-dimension empty array
empty = np.empty((2,3))
print(empty)
print('----------------')
# printing specific row
print(f"The row of index 1 is: {empty[1]}")
print('----------------')
# printing specific element
print(f"The value of index row 1 and column 2 is: {empty[1,2]}")   # where [row index, column index]

[[3.47739925e-081 1.90221768e-052 9.95595002e-047]
 [1.45088045e-047 1.93499724e+184 1.29441743e-312]]
----------------
The row of index 1 is: [1.45088045e-047 1.93499724e+184 1.29441743e-312]
----------------
The value of index row 1 and column 2 is: 1.29441743275e-312


### Basic array creation

- create an array with a range of elements using `arange` function

In [26]:
# simple array from 'arange'
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


- specify the first number, last number, and the step size

In [31]:
# simple array from 'arange' with step
arr = np.arange(10,20,3)    # here (start, end, step_size)
print(arr)

[10 13 16 19]


- create an array with values that are spaced linearly in a specified interval using `linspace` function

In [35]:
lin = np.linspace(0, 20, num=10) 
# (start, end, num='specify how many linearly spaced values you want in given range')
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

- Datatype can also be specified while creating an array

In [36]:
# specifying data type creating ones array
ones = np.ones((2,3), dtype=np.int16)
print(ones)
ones.dtype

[[1 1 1]
 [1 1 1]]


dtype('int16')

### Adding, Removing and Sorting Elements of array

In [43]:
# making a random array
arr = np.array([2,4,5,2,8,9,2,4,6,3,6,8])
arr

array([2, 4, 5, 2, 8, 9, 2, 4, 6, 3, 6, 8])

In [49]:
# sorting array in ascending order
np.sort(arr)


array([2, 2, 2, 3, 4, 4, 5, 6, 6, 8, 8, 9])

In [48]:
# sorting array in descending order
np.sort(arr)[::-1]

array([9, 8, 8, 6, 6, 5, 4, 4, 3, 2, 2, 2])

- concatenation of arrays

In [52]:
# two sample arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [53]:
# concatenate arr1 and arr2
arr3 = np.concatenate((arr1, arr2))
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Note:** In multi-dimension concatenation, all the input array dimensions except for the concatenation axis must match exactly.

In [62]:
# concatenation of multi-dimension array
a = np.array([[1,2,3],[4,5,6]]) # 2x3 array
b = np.array([[1,3,5]]) # 1x3 array

In [63]:
# concatenation
c = np.concatenate((a,b))
c

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 5]])

- To concatenate along `axis=1`, number of columns of both arrays must be equal.

In [64]:
# two multi-dimension arrays with same number of columns
a = np.array([[1,2,3],[4,5,6]]) # 2x3 array
b = np.array([[1,3,5],[7,8,9]]) # 2x3 array

In [66]:
# concatenation
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 7, 8, 9]])