# **3D Arrays**

In [1]:
# import libraries
import numpy as np

In [3]:
# create three dimensional array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [4]:
# checking dimension
array_example.ndim

3

In [5]:
# length of array
len(array_example)

3

In [6]:
# datatype of array
array_example.dtype

dtype('int64')

In [7]:
# shape of array
array_example.shape

(3, 2, 4)

- **Note:** `(x, y, z):`
    - x: number of 2D arrays present in 3D array
    - y: number of rows of each 2D array present
    - z: number of columns of each 2D array present

In [9]:
# create 3D array of (2,3,5)
a3 = np.array([[[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]],
                [[16,17,18,19,20]
                 ,[21,22,23,24,25],
                 [26,27,28,29,30]]])

a3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

- Reshaping the 3D array

In [13]:
a4 = a3.reshape(5, 6)
a4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

- **Note:** The size of the array must remain contant. For example in above `a3` array size was 30 as 2x3x5=30 so can only be reshaped into either 6x5 or 5x6.
- This can also be done to convert 2D into 3D with same logic.

In [16]:
a5 = a4.reshape(1,10,3)
a5

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]])

### Converting 1D array into 2D array

In [17]:
# create 1D array
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [24]:
# convert into 2D array
a2 = a1[np.newaxis, :]
print(a2)
print("------------")
print(a2.shape)

[[1 2 3 4]]
------------
(1, 4)


In [23]:
# convert into 3D array
a3 = a2[np.newaxis, :]
print(a3)
print("------------")
print(a3.shape)

[[[1 2 3 4]]]
------------
(1, 1, 4)


- These have been converted by addition of row, let's have a look how column addition works.

In [25]:
# convert into 2D array by column addition
a4 = a1[: , np.newaxis]
print(a4)
print("------------")
print(a4.shape)

[[1]
 [2]
 [3]
 [4]]
------------
(4, 1)


### Indexing and slicing

In [27]:
# sample array
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

- Indexing starts from `0` and in reverse order it starts from `-1` so some slicing examples are as follow:

In [33]:
# specific index
a[1]

np.int64(2)

In [34]:
# given index and all susequent indices
a[3:]

array([4, 5, 6, 7, 8])

In [35]:
# range of index
a[3:7]

array([4, 5, 6, 7])

In [37]:
# negative indices
a[-3:]

array([6, 7, 8])

- Slicing of 2D array

In [39]:
# a 2D array
a2 = np.array([[1,2,3,4,5],[7,8,9,1,2],[2,5,7,2,7]])
a2

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 1, 2],
       [2, 5, 7, 2, 7]])

In [48]:
# slicing
a2[0:, 1:]

array([[2, 3, 4, 5],
       [8, 9, 1, 2],
       [5, 7, 2, 7]])

In [50]:
# operation based slicing
a2[a2 > 5]

array([7, 8, 9, 7, 7])

In [51]:
# slicing based on remainder
a2[a2 % 2 == 0]

array([2, 4, 8, 2, 2, 2])

In [54]:
# slicing on more than one condition using boolen operators
a2[(a2 > 2) & (a2 < 7)]

array([3, 4, 5, 5])