# **Numpy**

In [1]:
# import library
import numpy as np

### Making an array from existing data

In [2]:
# let define an array
arr = np.arange(0, 220, 5)
arr

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215])

In [3]:
len(arr)

44

In [4]:
# slicing to make new array
array1 = arr[34:40]
array1

array([170, 175, 180, 185, 190, 195])

### Stacking arrays

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,1])

In [6]:
# vertical stacking both arrays
c = np.vstack((a,b))
c

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [7]:
# horizontal stacking both arrays
d = np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

- This thing is same as `concatenate`