# **Numpy: Matrices**

In [1]:
import numpy as np

- Actually, 2D arrays are matrices!

In [2]:
# create 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# create big matrix
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [8]:
# slicing this matrix
b[2:4,3:5]  # [row slicer, column slicer]

array([[46, 48],
       [66, 68]])

- Max. and Min. values from matrix

In [9]:
# max value
b.max()

np.int64(98)

In [10]:
# min value
b.min()

np.int64(0)

- sum of all enteries of matrix

In [11]:
# sum
b.sum()

np.int64(2450)

In [12]:
# min value in column
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# max values in rows
b.max(axis=1)

array([18, 38, 58, 78, 98])

### Addition or deletion in matrix

In [14]:
m = np.arange(0, 20, 2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

- **Note:** Here values are added in subsequent entries of matrix. If row addition is desired then `concatenate` or `vstack` or `hstack` funtion should be used.

In [16]:
# addition in matrix
m + np.array([1,1])
# similarly any other operation can also be used

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

### Flipping an array

In [18]:
# flipping matrix
np.flip(m)

array([[18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4],
       [ 2,  0]])